src-K/Group/urls.py
from django.urls import path

from Group.views import generate_groups, GroupsListView, GroupsUpdateView

app_name = 'groups'

urlpatterns = [
    path('gen_groups/', generate_groups, name='g-grp'),

    # path('', groups_list, name='list'),
    path('', GroupsListView.as_view(), name='list'),

    # path('edit/<int:id>', groups_edit, name='edit'),
    path('edit/<int:pk>', GroupsUpdateView.as_view(), name='edit'),
]

src-K/app_Kost_proj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

from app_Kost_proj import settings
from user_account.views import success_func

urlpatterns = [

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('success/', success_func, name='success'),

    path('account/', include('user_account.urls')),

    path('admin/', admin.site.urls, name='adm'),

    path('teachers/', include('teacher.urls')),

    path('students/', include('student.urls')),

    path('groups/', include('Group.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src-K/student/urls.py
from django.urls import path

from student.views import generate_students, StudentListView, StudentUpdateView, \
    StudentCreateView, StudentDeleteView

app_name = 'students'

urlpatterns = [

    path('gen_stud/', generate_students, name='g-stud'),

    # path('', students_list, name='list'),
    path('', StudentListView.as_view(), name='list'),

    # path('add/', students_add, name='add'),
    path('add/', StudentCreateView.as_view(), name='add'),

    # path('edit/<int:id>', students_edit, name='edit'),
    path('edit/<int:pk>', StudentUpdateView.as_view(), name='edit'),

    # path('delete/<int:id>', students_delete, name='delete'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='delete'),
]

src-K/teacher/urls.py
from django.urls import path

from teacher.views import generate_teachers, TeacherListView, TeacherCreateView, \
    TeacherUpdateView

app_name = 'teachers'

urlpatterns = [
    path('gen_teach/', generate_teachers, name='g-teach'),


    # path('', teachers_list, name='teachers'),
    path('', TeacherListView.as_view(), name='list'),

    # path('add/', teachers_add),
    path('add/', TeacherCreateView.as_view(), name='add'),

    # path('edit/<int:id>', teachers_edit, name='edit'),
    path('edit/<int:pk>', TeacherUpdateView.as_view(), name='edit'),

]

src-K/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>


<div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index'%}">LMS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'students:list'%}">Students <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:list'%}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'teachers:list'%}">Teachers</a>
                </li>
            </ul>

            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <div class="media">
                        <div class="img-circle.vert">
                            <img class="rounded-circle p-1 m-1" width="40" height="50" src="{{ user.profile.image.url }}">
                        </div>
                    </div>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'profile'%}">Profile </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                    </li>

                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'registration'%}">Register <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login'%}">Login</a>
                    </li>

                {% endif %}
            </ul>

<!--            <form class="form-inline my-2 my-lg-0">-->
<!--                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--            </form>-->

        </div>
    </nav>

    {% if messages %}
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <h3 class="p-4">{{title}}</h3>
    <p></p>
    {% if user.is_authenticated %}
        Logged in
    {% else %}
        Not logged in
    {% endif %}
    <p></p>
    {% block content%}
    {% endblock%}

</div>

</body>
</html>

src-K/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to K-LMS</h1>

{% endblock %}

src-K/templates/pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
    {% endif %}

    <li class="page-item"><a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}</a></li>

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
    {% endif %}
</ul>

src-K/templates/success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Success page!</h1>

{% endblock %}